**Task 2: Real-World ML Examples**
1. List 5 ML applications  
2. Explain spam detection  
3. Explain recommendation system

# List 5ML Applications

#### 1.Spam Email Detection
Identifies spam or fake emails automatically.
#### 2.Recommendation Systems
Suggests movies, videos, or products on platforms like Netflix and YouTube.
#### 3.Face Recognition
Used in mobile face unlock and security systems.
#### 4.Traffic Prediction
Google Maps predicts traffic and suggests faster routes.
#### 5.Self-Driving Cars
Cars use ML to detect roads, signals, and obstacles automatically.

# Explain spam detection
Spam detection is a Machine Learning application used to identify unwanted or fake emails automatically.

These unwanted emails are called:

Spam Emails

#### Examples of spam emails:

* Fake lottery messages
* Fraud links
* Advertisement emails
* Scam messages
### How Spam Detection Works
#### Step 1: Collect Email Data

The ML system is trained using many emails.

The emails are labeled as:

* Spam
* Not Spam
#### Step 2: Learn Patterns

The Machine Learning model studies common spam characteristics such as:

* Suspicious words
* Unknown links
* Repeated advertisements
* Dangerous attachments
* Excessive capital letters

**Example spam message:**

Congratulations! You won $1,000,000!
Click here now!

The ML model learns that such messages are usually spam.

#### Step 3: Prediction

When a new email arrives:

* The ML model analyzes the content
* Compares it with learned patterns
* Predicts whether it is spam or not

###### If detected as spam:

Email is moved to Spam Folder

# Explain recommendation system

A Recommendation System is a Machine Learning application that suggests products, movies, videos, or songs based on user interests and behavior.

It helps users find content they may like automatically.

#### How Recommendation System Works
##### Step 1: Collect User Data

The system collects information such as:

* Search history
* Watch history
* Likes and ratings
* Purchased products
* User interests
##### Step 2: Analyze Patterns

The Machine Learning model studies:

* What the user likes
* Similar users’ interests
* Frequently watched or purchased items

The system identifies patterns in user behavior.

##### Step 3: Give Recommendations

Based on learned patterns, the system suggests similar content or products.<br>
**Example:**
If a user watches:

* AI videos
* Python tutorials
* Data Science content

**Then YouTube recommends:**

* Machine Learning tutorials
* Coding videos
* AI project videos

**Task 3: Supervised Learning Practice**
1. Create student marks dataset  
2. Identify features & labels  
3. Explain prediction logic

In [3]:
import pandas as pd

In [4]:
# Creating student mark  dataset
data = {
    "Study_Hours": [1, 2, 3, 4, 5, 6, 7],
    "Marks": [25, 40, 50, 65, 75, 85, 95]
}

df = pd.DataFrame(data)

# Print dataset
df

   Study_Hours  Marks
0            1     25
1            2     40
2            3     50
3            4     65
4            5     75
5            6     85
6            7     95

##### Identifying feature and label
**Feature(Input)**  
**Study_Hours** <br>

**Label(Output)**  
**Marks**

#### Explain the prediction logic
The model learns the relation between studyhours and marks.

if the study hours increases marks also increases. The ML model studies the previous data and predicts the future values

**Task 4: Unsupervised Learning Practice** 
1. Customer grouping example  
2. Pattern finding example  
3. Clustering example

# Customer grouping example

In [10]:

data = {
    "Customer": ["A", "B", "C", "D", "E"],
    "Purchase_Amount": [500, 520, 5000, 4800, 550]
}

df = pd.DataFrame(data)

df

  Customer  Purchase_Amount
0        A              500
1        B              520
2        C             5000
3        D             4800
4        E              550

# Output Explanation (Prediction)
In Unsupervised Learning, the machine learns without correct answers.

The ML model studies customer purchase behavior and automatically creates groups based on similarities.

* Example Groups
* Normal customers
* Premium customers

This process is called:<br>
     <br>**Customer Segmentation**

Used in:

* Shopping apps
* Marketing analysis
* Recommendation systems

# Pattern Finding Example

In [11]:
data = {
    "Customer": ["A", "B", "C"],
    "Products_Bought": [
        "Mobile, Earphones",
        "Laptop, Mouse",
        "Mobile, Charger"
    ]
}

df = pd.DataFrame(data)

df

  Customer    Products_Bought
0        A  Mobile, Earphones
1        B      Laptop, Mouse
2        C    Mobile, Charger

# Output Explanation  (Prediction)
The ML system studies hidden relationships in data.<br>
**Example Pattern**<br>
Customers buying mobiles often buy accessories

The machine identifies:

* Similar buying habits
* Frequently purchased items
* Common customer interests

This helps businesses:

* Recommend products
* Improve sales
* Understand customer behavior

# Clustering Example

In [12]:
data = {
    "Student": ["A", "B", "C", "D"],
    "Marks": [95, 92, 45, 40]
}

df = pd.DataFrame(data)

df

  Student  Marks
0       A     95
1       B     92
2       C     45
3       D     40

# Output Expanation (Prediction)
**Clustering means:**<br>

Grouping similar data together
The ML model automatically groups students based on marks.<br>

**Example Clusters**<br>
* High Performers<br>
A<br>
B<br>
* Low Performers<br>
C<br>
D<br>

Clustering is widely used in:

* Customer grouping
* Image recognition
* Market analysis
* Pattern detection

**Task 5: Reinforcement Learning Practice** 
1. Robot learning example  
2. AI game example  
3. Reward/penalty explanation

# Robot learning Example

In [1]:
#Dataset or Situvation created
robot_actions = {
    "Correct_Move": "Reward",
    "Wrong_Move": "Penalty"
}

robot_actions

{'Correct_Move': 'Reward', 'Wrong_Move': 'Penalty'}

##### Explanation
In reinforcement learning the robot learning through  
Rewards and Penalties
A robot tries to walk:

If it walks correctly → Reward<br>
If it falls down → Penalty<br>

After many attempts, the robot learns the best way to walk.

This learning happens through:  
Trial and Error

# Ai game example

In [2]:
#Ai game Example
game_actions = {
    "Win_Game": "Reward",
    "Lose_Game": "Penalty"
}

print(game_actions)

{'Win_Game': 'Reward', 'Lose_Game': 'Penalty'}

#### Explanation
AI systems learn games by repeatedly playing them.

Example

In a chess game:

Good move → Reward
Bad move → Penalty

The AI studies:

Winning strategies
Opponent moves
Best decisions

Over time, the AI becomes smarter and improves gameplay.

# Reward/Penalty Explanation

##### Reward
Positive feedback for correct action

Examples:

* Robot walks properly
* AI wins a game
* Self-driving car avoids accident

#### Penalty
Negative feedback for wrong action

Examples:

* Robot falls
* AI loses game
* Car hits obstacle

#### Learning Process
Correct Action → Reward → Repeat Action

Wrong Action → Penalty → Avoid Action

The machine gradually learns the best possible behavior.