In [18]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
#Avoid Warnings
import warnings
warnings.filterwarnings('ignore')

# **Task 2: Dataset Practice** 
1. Create student dataset  
2. Create salary dataset  
3. Create sales dataset

In [15]:
#Create Student dataset

student_data = {
    
    'Study_Hours':[1,2,3,4,5,6,7,8],
    'Marks':[20,30,40,50,60,70,80,90]

}

student_df = pd.DataFrame(student_data)

student_df

   Study_Hours  Marks
0            1     20
1            2     30
2            3     40
3            4     50
4            5     60
5            6     70
6            7     80
7            8     90

In [28]:
#Create Salary dataset
salary_data =  {
   
    'Experience': [1,2,3,4,5],
    'Salary': [25000,35000,45000,55000,65000]
}

salary_df = pd.DataFrame(salary_data)

salary_df

   Experience  Salary
0           1   25000
1           2   35000
2           3   45000
3           4   55000
4           5   65000

In [33]:
#create sales dataset
sales_data = {
    'Month_Number': [1,2,3,4,5],
    'Sales': [20000,25000,30000,35000,40000]
}

sales_df = pd.DataFrame(sales_data)

sales_df

   Month_Number  Sales
0             1  20000
1             2  25000
2             3  30000
3             4  35000
4             5  40000

# **Task 3: Model Training** 
1. Train linear regression model  
2. Use fit()  
3. Understand learning process

# Train linear regression model
A Linear Regression model is used to predict numerical values based on input data.

Example:

Study hours → Marks
Experience → Salary

# Training student dataset

In [16]:
# Features and Label
X = student_df[['Study_Hours']]  # Input/Feature data or Independent variable
y = student_df[['Marks']]        #Output/Label or Dependent variable

#Create model
model = LinearRegression()

#Usefit
model.fit(X,y)    #fit() function is used to train machine learning model

print("Model Training completed")

Model Training completed

#### 3. Understand Learning Process
How the Model Learns
##### Step 1: Input Data

The model receives:

Features (study hours)
Labels (marks)
#### Step 2: Pattern Finding

The model identifies relationships.

Example:

More study hours → Higher marks
#### Step 3: Create Mathematical Relationship

Linear Regression learns a straight-line relationship:
y=mx+b
Where:

y = predicted output
x = input feature
m = slope

#### Step 4: Prediction

After learning, the model predicts outputs for new data.

# Training the salary dataset

In [30]:

#Feature and Label
X= salary_df[["Experience"]]
y= salary_df[["Salary"]]

#Train Model
model = LinearRegression()
#Use fit
model.fit(X,y)

print("Model training completed")

Model training completed

# Training Sales values

In [36]:
#Features and Label
X= sales_df[["Month_Number"]]
y= sales_df[["Sales"]]

#Train Model
model =  LinearRegression()
#Use fit
model.fit(X,y)

print("Model training completed")

Model training completed

# **Task 4: Prediction Practice**
1. Predict marks  
2. Predict salary  
3. Predict sales values

In [22]:
#Predict marks
prediction = model.predict([[10]])
print("Predicted Marks:", prediction)

Predicted Marks: [[110.]]

In [31]:
#Predict Salary
prediction = model.predict([[6]])
print("Predicted Salary:",prediction)

Predictrd Salary: [[75000.]]

In [37]:
#Predict Sales Values
prediction = model.predict([[6]])
print("Predicted Salary:",prediction)

Predicted Salary: [[45000.]]

# **Task 5: Feature & Label Identification** 
1. Identify input/output  
2. Explain X and y  
3. Explain training logic

# Identify input and Output
In Machine Learning, data is divided into:

* Input data → Feature
* Output data → Label<br>
###### In Student Dataset
* input-->Study_Hours
* output-->Marks
###### In Salary Dataset
* input--->Experience
* output-->Salary
###### In Sales data set
* input---->Month Number
* output--->Sales

# Explain X and Y
### Meaning of X
## X

#### Represents:

#### Features
* Input variables
* Independent variables<br>

**Example:**

Study hours
Experience
Month Number
### Meaning of y
## y

#### Represents:

#### Labels
* Output variables
* Target values

**Example:**

* Marks
* Salary
* Sales

# Explain Training Logic
Training means teaching the ML model using data.
### Step 1: Give Input Data

The model receives features (X).<br>

**Example:** <br>

* Study hours
### Step 2: Give Correct Output

The model receives labels (y).<br>

**Example:** <br>

* Marks
### Step 3: Learn Relationship

The model identifies patterns between input and output.<br>

**Example:** <br>

* Higher study hours → Higher marks
### Step 4: Create Prediction Formula

* Linear Regression learns a relationship:
  y=mx+b
Where:<br>

y = output<br>
x = input<br>
m = slope<br>
b = intercept<br>
### Step 5: Predict New Values

After training, the model predicts outputs for new inputs.<br>

**Example:** <br>

Study Hours = 7<br>
Predicted Marks = 85<br>

fit() function is used to training the model

# **Task 6: Real-World ML Examples** 
1. House price prediction  
2. Weather prediction  
3. Employee salary prediction

# 1. House Price Prediction

Machine Learning is widely used to predict house prices based on property details.

### Features Used
* Area of house
* Number of bedrooms
* Location
* Parking facility
### Label
* House price
### Example
| Area (sq.ft) | Bedrooms | Price    |
| ------------ | -------- | -------- |
| 1000         | 2        | 35 Lakhs |
| 1500         | 3        | 50 Lakhs |
| 2000         | 4        | 75 Lakhs |

**The ML model learns:**<br>

* Larger houses → Higher prices

# 2. Weather Prediction

Machine Learning helps forecast weather conditions using historical climate data.

### Features Used
* Temperature
* Humidity
* Wind speed
* Air pressure
### Label
* Rain or No Rain
* Temperature forecast
### Example
| Temperature | Humidity | Prediction |
| ----------- | -------- | ---------- |
| 32°C        | 80%      | Rain       |
| 25°C        | 45%      | No Rain    |

The model identifies weather patterns and predicts future conditions.

# 3. Employee Salary Prediction

ML models can predict employee salary based on experience and qualifications.

### Features Used
* Years of experience
* Education level
* Skills
* Job role
### Label
* Salary
### Example
| Experience | Education | Salary   |
| ---------- | --------- | -------- |
| 1 Year     | UG        | 25,000   |
| 5 Years    | PG        | 60,000   |
| 10 Years   | PhD       | 1,00,000 |

The model learns:

More experience and higher education → Higher salary